import type { Finding } from "../footnote-engine/types";
import type { ProposedReviewAction, ReviewPolicy } from "./types";

const AUTO_TEXT: ReviewPolicy = {
  reviewClass: "AUTO",
  reason: "DETERMINISTIC_TEXT_CHANGE",
};
const AUTO_FORMAT: ReviewPolicy = {
  reviewClass: "AUTO",
  reason: "DETERMINISTIC_FORMAT_CHANGE",
};

export const REVIEW_POLICY_REGISTRY = {
  FINAL_PERIOD: { reviewClass: "AUTO", reason: "SAFE_INSERTION" },
  CITATION_PINPOINT_BRACKETS: { reviewClass: "AUTO", reason: "SAFE_INSERTION" },
  EMPTY_FOOTNOTE: { reviewClass: "MANUAL", reason: "SEMANTIC_UNCERTAINTY" },

  STATUTE_PARAGRAPH_STYLE: AUTO_TEXT,
  STATUTE_SENTENCE_STYLE: AUTO_TEXT,
  STATUTE_LETTER_STYLE: AUTO_TEXT,
  STATUTE_ALTERNATIVE_STYLE: AUTO_TEXT,
  STATUTE_VARIANT_STYLE: AUTO_TEXT,
  STATUTE_MULTIPLE_SECTION_SEPARATOR: AUTO_TEXT,
  STATUTE_ABBREVIATION_STYLE: AUTO_TEXT,
  STATUTE_FOLLOWING_SUFFIX_STYLE: AUTO_TEXT,

  CASE_LAW_DECISION_TYPE: AUTO_TEXT,
  CASE_LAW_DATE_INTRODUCER: AUTO_TEXT,
  CASE_LAW_DATE_FORMAT: AUTO_TEXT,
  CASE_LAW_DOCKET_SEPARATOR: AUTO_TEXT,
  CASE_LAW_PARALLEL_SEPARATOR: AUTO_TEXT,
  CASE_LAW_OFFICIAL_COLLECTION_PINPOINT_STYLE: AUTO_TEXT,
  CASE_LAW_JOURNAL_PINPOINT_STYLE: AUTO_TEXT,

  COMMENTARY_WORK_NAME: {
    reviewClass: "AUTO",
    reason: "SAFE_MAPPING_NORMALIZATION",
  },
  COMMENTARY_PERSON_SEPARATOR: AUTO_TEXT,
  COMMENTARY_MARGIN_NUMBER_ABBREVIATION: AUTO_TEXT,
  COMMENTARY_FORMATTING: AUTO_FORMAT,

  BOOK_PERSON_SEPARATOR: AUTO_TEXT,
  BOOK_MARGIN_NUMBER_ABBREVIATION: AUTO_TEXT,
  BOOK_PAGE_ABBREVIATION: AUTO_TEXT,
  BOOK_EDITION_ABBREVIATION: AUTO_TEXT,
  BOOK_WORK_SECTION_STYLE: AUTO_TEXT,
  BOOK_AUTHOR_FORMATTING: AUTO_FORMAT,

  JOURNAL_WORK_NAME: {
    reviewClass: "AUTO",
    reason: "SAFE_MAPPING_NORMALIZATION",
  },
  JOURNAL_PINPOINT_STYLE: AUTO_TEXT,
  JOURNAL_PERSON_SEPARATOR: AUTO_TEXT,
  JOURNAL_AUTHOR_FORMATTING: AUTO_FORMAT,
  JOURNAL_FOLLOWING_SUFFIX_STYLE: AUTO_TEXT,

  FORMAT_FONT_NAME: AUTO_FORMAT,
  FORMAT_FONT_SIZE: AUTO_FORMAT,
  FORMAT_BOLD: AUTO_FORMAT,
  FORMAT_ITALIC_REVIEW: { reviewClass: "MANUAL", reason: "UNKNOWN_ROLE" },
  FORMAT_UNDERLINE: AUTO_FORMAT,
  FORMAT_STRIKE: AUTO_FORMAT,
  FORMAT_SUPERSCRIPT: AUTO_FORMAT,
  FORMAT_SUBSCRIPT: AUTO_FORMAT,
  FORMAT_CHARACTER_SPACING: AUTO_FORMAT,

  CASE_NOTE_STYLE: AUTO_TEXT,
  BOOK_CHAPTER_STYLE: AUTO_TEXT,
  LEGISLATIVE_MATERIAL_PREFIX: AUTO_TEXT,
  ONLINE_SOURCE_ACCESS_DATE: AUTO_TEXT,
  ADMINISTRATIVE_MATERIAL_DATE: AUTO_TEXT,
  CITATION_MODIFIER_STYLE: AUTO_TEXT,
  CITATION_BOUNDARY_CAPITALIZATION: AUTO_TEXT,
  BOOK_AUTHOR_TITLE_SEPARATOR: { reviewClass: "AUTO", reason: "SAFE_INSERTION" },
  GENERIC_ABBREVIATION_STYLE: AUTO_TEXT,

  CUSTOM_SOURCE_PREFERRED_CITATION: {
    reviewClass: "MANUAL",
    reason: "SEMANTIC_UNCERTAINTY",
  },
  CITATION_OTHER_REVIEW: { reviewClass: "MANUAL", reason: "UNKNOWN_CITATION_TYPE" },
  CITATION_EXTRACTION_UNRESOLVED: {
    reviewClass: "MANUAL",
    reason: "SEMANTIC_UNCERTAINTY",
  },
  SOURCE_MAPPING_AMBIGUOUS: { reviewClass: "MANUAL", reason: "AMBIGUOUS_MAPPING" },
  SOURCE_MAPPING_LEGACY_UNCERTAIN: {
    reviewClass: "INFO",
    reason: "INFORMATION_ONLY",
  },
  SOURCE_NAME_CONSISTENCY: {
    reviewClass: "MANUAL",
    reason: "CONSISTENCY_DECISION_REQUIRED",
  },
  SOURCE_CITATION_VARIANT_CONSISTENCY: {
    reviewClass: "MANUAL",
    reason: "CONSISTENCY_DECISION_REQUIRED",
  },
  CITATION_STYLE_CONSISTENCY: {
    reviewClass: "MANUAL",
    reason: "CONSISTENCY_DECISION_REQUIRED",
  },
  FORMATTING_CONSISTENCY: {
    reviewClass: "MANUAL",
    reason: "CONSISTENCY_DECISION_REQUIRED",
  },
  RULE_OUTPUT_INVALID: { reviewClass: "TECHNICAL", reason: "ACTION_NOT_BUILDABLE" },
  RULE_REPLACEMENT_CONFLICT: {
    reviewClass: "TECHNICAL",
    reason: "CONFLICTING_ACTION",
  },
} as const satisfies Record<string, ReviewPolicy>;

export type RegisteredReviewPolicyRuleId = keyof typeof REVIEW_POLICY_REGISTRY;

export function reviewPolicyFor(
  finding: Finding,
  proposedAction?: ProposedReviewAction
): ReviewPolicy {
  const policy = REVIEW_POLICY_REGISTRY[finding.ruleId as RegisteredReviewPolicyRuleId];
  if (policy) return policy;
  return proposedAction
    ? { reviewClass: "MANUAL", reason: "SEMANTIC_UNCERTAINTY" }
    : { reviewClass: "INFO", reason: "NO_ACTION_AVAILABLE" };
}

export function missingReviewPolicyRuleIds(ruleIds: readonly string[]): string[] {
  return Array.from(new Set(ruleIds))
    .filter((ruleId) => !(ruleId in REVIEW_POLICY_REGISTRY))
    .sort();
}
